name: CI - Selenium Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html allure-pytest

      - name: Install Chrome 114.0.5735.90 manually
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/114.0.5735.90/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome114
          sudo ln -sf /opt/chrome114/chrome /usr/bin/google-chrome

      - name: Install ChromeDriver 114.0.5735.90
        run: |
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Confirm Installed Versions
        run: |
          echo "✅ Chrome version: $(google-chrome --version)"
          echo "✅ ChromeDriver version: $(chromedriver --version)"

      - name: Create test results directory
        run: |
          mkdir -p test-results/screenshots
          mkdir -p test-results/allure

      - name: Run Tests
        run: |
          find . -maxdepth 1 -name "*.png" -delete || true
          
          pytest tests/ \
            --disable-warnings \
            --maxfail=2 \
            --html=test-results/report.html \
            --self-contained-html \
            --alluredir=test-results/allure \
            --reruns 2 \
            --reruns-delay 1
          
          find . -maxdepth 1 -name "*.png" -exec mv {} test-results/screenshots/ \; || true

      - name: Upload all test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: test-results/
