name: CI - Selenium Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Headless Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-browser
          sudo ln -s /usr/bin/chromium-browser /usr/bin/chrome

      - name: Run Tests (Headless)
        run: |
          pytest tests/ --disable-warnings --maxfail=2

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-screenshots
          path: "*.png"