name: CI - Selenium Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html allure-pytest

      - name: Set up Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip curl
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # - name: Install matching ChromeDriver for installed Chrome
      #   run: |
      #     set -e

      #     # Get Chrome version
      #     CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
      #     echo "Detected Chrome version: $CHROME_VERSION"

      #     # If Chrome version is empty, fail early
      #     if [ -z "$CHROME_VERSION" ]; then
      #       echo "Failed to detect Chrome version"
      #       exit 1
      #     fi

      #     # Get matching ChromeDriver version
      #     CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
      #     echo "Matching ChromeDriver version: $CHROMEDRIVER_VERSION"

      #     # Download and install
      #     wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      #     unzip -o chromedriver_linux64.zip
      #     sudo mv -f chromedriver /usr/bin/chromedriver
      #     sudo chmod +x /usr/bin/chromedriver


      - name: Create test results directory
        run: |
          mkdir -p test-results/screenshots
          mkdir -p test-results/allure

      - name: Run Tests
        run: |
          find . -maxdepth 1 -name "*.png" -delete || true
          
          pytest tests/ \
            --disable-warnings \
            --maxfail=2 \
            --html=test-results/report.html \
            --self-contained-html \
            --alluredir=test-results/allure \
            --reruns 2 \
            --reruns-delay 1
          
          find . -maxdepth 1 -name "*.png" -exec mv {} test-results/screenshots/ \; || true

      - name: Upload all test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: test-results/
