name: CI - Selenium Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html allure-pytest

      - name: Set up Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/bin/chromium-browser /usr/bin/chrome
          echo "CHROMEDRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Create test results directory
        run: |
          mkdir -p test-results/screenshots
          mkdir -p test-results/allure

      - name: Run Tests
        run: |
          # Clear root PNGs before running tests
          find . -maxdepth 1 -name "*.png" -delete || true
          
          pytest tests/ \
            --disable-warnings \
            --maxfail=2 \
            --html=test-results/report.html \
            --self-contained-html \
            --alluredir=test-results/allure \
            --reruns 2 \
            --reruns-delay 1
          
          # Move all screenshots to the folder (if any were left outside)
          find . -maxdepth 1 -name "*.png" -exec mv {} test-results/screenshots/ \; || true

      - name: Upload all test artifacts
        uses: actions/upload-artifact@v4   # ✅ Updated from v3 to v4
        if: always()
        with:
          name: test-artifacts
          path: test-results/
